site_name: Jewish Music Wiki
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - search.suggest
    - content.action.edit
repo_url: https://github.com/espire/jewishmusic
edit_uri: edit/main/docs/
hooks:
  - hooks/generate_index.py
markdown_extensions:
  - md_in_html
